version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: leave-management-backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mongo_data:
